# Generated by Django 2.1.7 on 2019-04-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='serve',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='serve',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
