# Generated by Django 2.1.7 on 2019-04-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0002_auto_20190404_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_style',
        ),
        migrations.RemoveField(
            model_name='user',
            name='not_eat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Urbana', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='IL', max_length=20),
            preserve_default=False,
        ),
    ]
