# Generated by Django 2.1.7 on 2019-03-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0003_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
