# Generated by Django 2.1.7 on 2019-04-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0004_auto_20190416_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Together',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyearth.User', unique=True)),
            ],
        ),
    ]
