# Generated by Django 2.1.7 on 2019-03-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0004_auto_20190317_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('price', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('ingredient', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='flavor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_style',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='not_eat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='religion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serve',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyearth.Dish'),
        ),
        migrations.AddField(
            model_name='serve',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyearth.Restaurant'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyearth.Dish'),
        ),
        migrations.AddField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyearth.Restaurant'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyearth.User'),
        ),
    ]
