# Generated by Django 2.1.7 on 2019-03-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0005_auto_20190321_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.CharField(blank=True, default='default review', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, default='default description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='flavor',
            field=models.CharField(blank=True, default='default flavor', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serve',
            name='ingredient',
            field=models.CharField(blank=True, default='default ingredient', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serve',
            name='size',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_style',
            field=models.CharField(blank=True, default='default style', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='not_eat',
            field=models.CharField(blank=True, default='default noteat', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=2222222, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, default='default religion', max_length=100),
            preserve_default=False,
        ),
    ]
