# Generated by Django 2.1.7 on 2019-03-22 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0006_auto_20190321_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happyearth.Dish'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happyearth.Dish'),
        ),
    ]
