# Generated by Django 2.1.7 on 2019-04-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyearth', '0006_auto_20190424_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='id',
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
